

-- USE [master]; DROP DATABASE BIBLIOTECA;
-- DROP LOGIN biblioteca

USE [master];
GO

CREATE DATABASE BIBLIOTECA;
GO

CREATE LOGIN [biblioteca] WITH PASSWORD=N'biblioteca123', DEFAULT_DATABASE=[BIBLIOTECA], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;
GO

USE [BIBLIOTECA];
GO

CREATE USER [biblioteca] FOR LOGIN [biblioteca];
GO

ALTER USER [biblioteca] WITH DEFAULT_SCHEMA=[dbo];
ALTER AUTHORIZATION ON SCHEMA::[db_owner] TO [biblioteca];
ALTER ROLE [db_owner] ADD MEMBER [biblioteca]
GO

USE [BIBLIOTECA];
GO

/************************************************************************************************/
-- TABELAS DO NEGOCIO
/************************************************************************************************/
CREATE TABLE dbo.PRODUTO_TIPO
(
	ID_PRODUTO_TIPO INT NOT NULL IDENTITY(1, 1),
	DESCRICAO VARCHAR(120) NOT NULL,
	PRAZO INT NOT NULL DEFAULT 1,
	VL_MULTA DECIMAL(12, 2) NOT NULL DEFAULT 0,
	ATIVO BIT NOT NULL DEFAULT 1,
	CONSTRAINT PK_PROD_TIPO PRIMARY KEY (ID_PRODUTO_TIPO)
);
GO

CREATE TABLE dbo.AUTOR
(
	ID_AUTOR INT NOT NULL IDENTITY(1, 1),
	NOME VARCHAR(300) NOT NULL,
	DT_NASCIMENTO DATETIME NULL,
	CONSTRAINT PK_AUTOR PRIMARY KEY (ID_AUTOR)
);
GO

CREATE TABLE dbo.EDITORA
(
	ID_EDITORA INT NOT NULL IDENTITY(1, 1),
	NOME VARCHAR(300) NOT NULL,
	CONSTRAINT PK_EDITORA PRIMARY KEY (ID_EDITORA)
);
GO

CREATE TABLE dbo.PRODUTO
(
	ID_PRODUTO INT NOT NULL IDENTITY(1, 1),
	DESCRICAO VARCHAR(120) NOT NULL,
	ID_PRODUTO_TIPO INT NOT NULL,
	ID_AUTOR INT NOT NULL,
	ID_EDITORA INT NOT NULL,
	QUANTIDADE INT NOT NULL DEFAULT 0,
	ANO_PUBLICACAO INT,
	ISBN VARCHAR(100) NULL,
	ATIVO BIT NOT NULL DEFAULT 1,
	CONSTRAINT PK_PRODUTO PRIMARY KEY (ID_PRODUTO),
	CONSTRAINT FK_PROD_PRODTIPO FOREIGN KEY (ID_PRODUTO_TIPO) REFERENCES dbo.PRODUTO_TIPO (ID_PRODUTO_TIPO),
	CONSTRAINT FK_PROD_AUTOR FOREIGN KEY (ID_AUTOR) REFERENCES dbo.AUTOR (ID_AUTOR),
	CONSTRAINT FK_PROD_EDITORA FOREIGN KEY (ID_EDITORA) REFERENCES dbo.EDITORA (ID_EDITORA)
);
GO

CREATE TABLE dbo.GENERO
(
	ID_GENERO INT NOT NULL IDENTITY(1, 1),
	DESCRICAO VARCHAR(300) NOT NULL,
	CONSTRAINT PK_GENERO PRIMARY KEY (ID_GENERO)
);
GO

CREATE TABLE dbo.PRODUTO_GENERO
(
	ID_PRODUTO_GENERO INT NOT NULL IDENTITY(1, 1),
	ID_GENERO INT NOT NULL,
	ID_PRODUTO INT NOT NULL,
	PRINCIPAL BIT NOT NULL DEFAULT 0,
	CONSTRAINT PK_PRODUTO_GENERO PRIMARY KEY (ID_PRODUTO_GENERO),
	CONSTRAINT FK_PRODGEN_GENERO FOREIGN KEY (ID_GENERO) REFERENCES dbo.GENERO (ID_GENERO),
	CONSTRAINT FK_PRODGEN_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES dbo.PRODUTO (ID_PRODUTO)
);
GO

CREATE TABLE dbo.SEXO
(
	ID_SEXO SMALLINT NOT NULL IDENTITY(1, 1),
	DESCRICAO VARCHAR(100) NOT NULL,
	CONSTRAINT PK_SEXO PRIMARY KEY (ID_SEXO)
);
GO

CREATE TABLE dbo.CLIENTE
(
	ID_CLIENTE INT NOT NULL IDENTITY(1, 1),
	NOME VARCHAR(120) NOT NULL,
	DT_NASCIMENTO DATETIME NULL,
	ID_SEXO SMALLINT NULL,
	ATIVO BIT DEFAULT 1,
	CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE),
	CONSTRAINT FK_CLI_SEXO FOREIGN KEY (ID_SEXO) REFERENCES dbo.SEXO (ID_SEXO)
);
GO

CREATE TABLE dbo.USUARIO_GRUPO
(
	ID_USUARIO_GRUPO INT NOT NULL IDENTITY(1, 1),
	DESCRICAO VARCHAR(120) NOT NULL,
	ATIVO BIT NOT NULL DEFAULT 1,
	CONSTRAINT PK_USUARIO_GRUPO PRIMARY KEY (ID_USUARIO_GRUPO)
);
GO

CREATE TABLE dbo.USUARIO
(
	ID_USUARIO INT NOT NULL IDENTITY(1, 1),
	NOME VARCHAR(120) NOT NULL,
	DT_NASCIMENTO DATETIME NULL,
	ID_SEXO SMALLINT NULL,
	LOGIN VARCHAR(20) NOT NULL,
	SENHA VARCHAR(50) NOT NULL,
	DT_CADASTRO DATETIME NULL DEFAULT GETDATE(),
	ID_USUARIO_GRUPO INT NOT NULL,
	ATIVO BIT NOT NULL DEFAULT 1
	CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO)
	CONSTRAINT FK_USU_GRUPO FOREIGN KEY (ID_USUARIO_GRUPO) REFERENCES dbo.USUARIO_GRUPO (ID_USUARIO_GRUPO)
);
GO

CREATE TABLE dbo.PERMISSAO
(
	ID_PERMISSAO INT NOT NULL IDENTITY(1, 1),
	DESCRICAO VARCHAR(120) NOT NULL,
	OPERACAO VARCHAR(120) NOT NULL,
	ATIVO BIT NOT NULL DEFAULT 1,
	CONSTRAINT PK_PERMISSAO PRIMARY KEY (ID_PERMISSAO)
);
GO

CREATE TABLE dbo.USUARIO_GRUPO_PERM
(
	ID_USUARIO_GRUPO_PERM INT NOT NULL IDENTITY(1, 1),
	ID_USUARIO_GRUPO INT NOT NULL,
	ID_PERMISSAO INT NOT NULL,
	CONSTRAINT PK_USU_GRUP_PERM PRIMARY KEY (ID_USUARIO_GRUPO_PERM),
	CONSTRAINT FK_USUGRUPPERM_USUGRUP FOREIGN KEY (ID_USUARIO_GRUPO) REFERENCES dbo.USUARIO_GRUPO (ID_USUARIO_GRUPO),
	CONSTRAINT FK_USUGRUPPERM_PERM FOREIGN KEY (ID_PERMISSAO) REFERENCES dbo.PERMISSAO (ID_PERMISSAO)
);
GO

CREATE TABLE dbo.LOCACAO
(
	ID_LOCACAO INT NOT NULL IDENTITY(1, 1),
	ID_PRODUTO INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	DT_LOCACAO DATETIME NOT NULL DEFAULT GETDATE(),
	DT_LIMITE_DEVOLUCAO DATETIME NOT NULL,
	DT_DEVOLUCAO DATETIME NULL,
	ID_USUARIO INT NOT NULL,
	CONSTRAINT PK_LOCACAO PRIMARY KEY (ID_LOCACAO),
	CONSTRAINT FK_LOCA_PROD FOREIGN KEY (ID_PRODUTO) REFERENCES dbo.PRODUTO (ID_PRODUTO),
	CONSTRAINT FK_LOCA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES dbo.CLIENTE (ID_CLIENTE),
	CONSTRAINT FK_LOCA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES dbo.USUARIO (ID_USUARIO)
);
GO

CREATE TABLE dbo.UF
(
	ID_UF INT NOT NULL IDENTITY(1, 1),
	DESCRICAO VARCHAR(120) NOT NULL,
	CONSTRAINT PK_UF PRIMARY KEY (ID_UF)
);
GO

CREATE TABLE dbo.CIDADE
(
	ID_CIDADE INT NOT NULL IDENTITY(1, 1),
	DESCRICAO VARCHAR(120) NOT NULL,
	ID_UF INT NOT NULL,
	CONSTRAINT PK_CIDADE PRIMARY KEY (ID_CIDADE),
	CONSTRAINT FK_CID_UF FOREIGN KEY (ID_UF) REFERENCES dbo.UF (ID_UF)
);
GO

/************************************************************************************************/
-- TABELAS DE CLIENTE
/************************************************************************************************/
CREATE TABLE dbo.CLIENTE_ENDERECO
(
	ID_CLIENTE_ENDERECO INT NOT NULL IDENTITY(1, 1),
	ID_CLIENTE INT NOT NULL,
	LOGRADOURO VARCHAR(300) NOT NULL,
	NUMERO VARCHAR(20) NULL,
	BAIRRO VARCHAR(200) NULL,
	CEP VARCHAR(20) NULL,
	ID_CIDADE INT NOT NULL,
	CONSTRAINT PK_CLI_ENDERECO PRIMARY KEY (ID_CLIENTE_ENDERECO),
	CONSTRAINT FK_CLIEND_CLI FOREIGN KEY (ID_CLIENTE) REFERENCES dbo.CLIENTE (ID_CLIENTE),
	CONSTRAINT FK_CLIEND_CID FOREIGN KEY (ID_CIDADE) REFERENCES dbo.CIDADE (ID_CIDADE)
);
GO

CREATE TABLE dbo.CLIENTE_EMAIL
(
	ID_CLIENTE_EMAIL INT NOT NULL IDENTITY(1, 1),
	ID_CLIENTE INT NOT NULL,
	EMAIL VARCHAR(300) NOT NULL,
	CONSTRAINT PK_CLIENTE_EMAIL PRIMARY KEY (ID_CLIENTE_EMAIL),
	CONSTRAINT FK_CLIEMAIL_CLI FOREIGN KEY (ID_CLIENTE) REFERENCES dbo.CLIENTE (ID_CLIENTE)
);
GO

CREATE TABLE dbo.CLIENTE_TELEFONE
(
	ID_CLIENTE_TELEFONE INT NOT NULL IDENTITY(1, 1),
	ID_CLIENTE INT NOT NULL,
	DDD SMALLINT NOT NULL,
	TELEFONE INT NOT NULL,
	CONSTRAINT PK_CLIENTE_TELEFONE PRIMARY KEY (ID_CLIENTE_TELEFONE),
	CONSTRAINT FK_CLIETELE_CLI FOREIGN KEY (ID_CLIENTE) REFERENCES dbo.CLIENTE (ID_CLIENTE)
);
GO

--/************************************************************************************************/
---- TABELAS DE USUARIO
--/************************************************************************************************/
--CREATE TABLE dbo.USUARIO_ENDERECO
--(
--	ID_USUARIO_ENDERECO INT NOT NULL IDENTITY(1, 1),
--	ID_USUARIO INT NOT NULL,
--	LOGRADOURO VARCHAR(300) NOT NULL,
--	NUMERO VARCHAR(20) NULL,
--	BAIRRO VARCHAR(200) NULL,
--	CEP VARCHAR(20) NULL,
--	ID_CIDADE INT NOT NULL,
--	CONSTRAINT PK_USU_ENDERECO PRIMARY KEY (ID_USUARIO_ENDERECO),
--	CONSTRAINT FK_USUEND_USU FOREIGN KEY (ID_USUARIO) REFERENCES dbo.USUARIO (ID_USUARIO),
--	CONSTRAINT FK_USUEND_CID FOREIGN KEY (ID_CIDADE) REFERENCES dbo.CIDADE (ID_CIDADE)
--);
--GO

--CREATE TABLE dbo.USUARIO_EMAIL
--(
--	ID_USUARIO_EMAIL INT NOT NULL IDENTITY(1, 1),
--	ID_USUARIO INT NOT NULL,
--	EMAIL VARCHAR(300) NOT NULL,
--	CONSTRAINT PK_USUENTE_EMAIL PRIMARY KEY (ID_USUARIO_EMAIL),
--	CONSTRAINT FK_USUEMAIL_USU FOREIGN KEY (ID_USUARIO) REFERENCES dbo.USUARIO (ID_USUARIO)
--);
--GO

--CREATE TABLE dbo.USUARIO_TELEFONE
--(
--	ID_USUARIO_TELEFONE INT NOT NULL IDENTITY(1, 1),
--	ID_USUARIO INT NOT NULL,
--	DDD SMALLINT NOT NULL,
--	TELEFONE INT NOT NULL,
--	CONSTRAINT PK_USUARIO_TELEFONE PRIMARY KEY (ID_USUARIO_TELEFONE),
--	CONSTRAINT FK_USUTELE_USU FOREIGN KEY (ID_USUARIO) REFERENCES dbo.USUARIO (ID_USUARIO)
--);
--GO


INSERT INTO USUARIO_GRUPO (DESCRICAO, ATIVO)
VALUES ('ADMINISTRADORES', 1);
GO

INSERT INTO USUARIO (NOME, LOGIN, SENHA, ID_USUARIO_GRUPO, ATIVO)
VALUES ('ADMINISTRADOR', 'ADMIN', '123456', 1, 1);
GO

INSERT INTO SEXO (DESCRICAO) VALUES ('MASCULINO'),('FEMININO');
GO

INSERT INTO CLIENTE (NOME, DT_NASCIMENTO, ATIVO, ID_SEXO)
VALUES	('JORGE AMADO BATISTA', '1984-03-23 00:00:00', 1, 1),
		('LUCAS FERREIRA', '1999-12-25 00:00:00', 1, 1),
		('DANIEL VACILO DA SILVA', '1983-02-28 00:00:00', 1, 1),
		('ANTONIA NUNES', '1995-07-30 00:00:00', 1, 2);
GO