SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Bruno Oliveira
-- Create date: 09/09/2018
-- Description:	Altera os registros da tabela PRODUTO_TIPO
-- =============================================
CREATE PROCEDURE dbo.PRC_IU_PRODUTOTIPO
	@I_ID_PRODUTO_TIPO INT,
	@I_DESCRICAO VARCHAR(120),
	@I_PRAZO INT,
	@I_VL_MULTA DECIMAL(12,2),
	@I_ATIVO BIT
AS
BEGIN
	SET NOCOUNT ON;

	IF EXISTS (SELECT TOP(1) ID_PRODUTO_TIPO FROM PRODUTO_TIPO WITH(NOLOCK) WHERE ID_PRODUTO_TIPO = @I_ID_PRODUTO_TIPO) BEGIN

		UPDATE PRODUTO_TIPO
		SET DESCRICAO	= UPPER(@I_DESCRICAO),
			PRAZO		= @I_PRAZO,
			VL_MULTA	= @I_VL_MULTA,
			ATIVO		= @I_ATIVO
		WHERE ID_PRODUTO_TIPO = @I_ID_PRODUTO_TIPO

	END
	ELSE BEGIN

		INSERT INTO PRODUTO_TIPO (DESCRICAO, PRAZO, VL_MULTA, ATIVO)
		VALUES (UPPER(@I_DESCRICAO), @I_PRAZO, @I_VL_MULTA, @I_ATIVO)

	END

	SET NOCOUNT OFF;
END
GO
