SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Bruno Oliveira
-- Create date: 11/09/2018
-- Description:	Insere ou altera produtos na base.
-- =============================================
CREATE PROCEDURE dbo.PRC_IU_PRODUTO
	@I_ID_PRODUTO INT,
	@I_DESCRICAO VARCHAR(120),
	@I_ID_PRODUTO_TIPO INT,
	@I_ID_AUTOR INT,
	@I_ID_EDITORA INT,
	@I_QUANTIDADE INT,
	@I_ATIVO BIT
AS
BEGIN
	SET NOCOUNT ON;

    IF EXISTS (SELECT TOP(1) ID_PRODUTO FROM PRODUTO WITH(NOLOCK) WHERE ID_PRODUTO = @I_ID_PRODUTO) BEGIN

		UPDATE PRODUTO
		SET DESCRICAO		= UPPER(@I_DESCRICAO),
			ID_PRODUTO_TIPO = @I_ID_PRODUTO_TIPO,
			ID_AUTOR		= @I_ID_AUTOR,
			ID_EDITORA		= @I_ID_EDITORA,
			QUANTIDADE		= @I_QUANTIDADE,
			ATIVO			= @I_ATIVO
		WHERE ID_PRODUTO = @I_ID_PRODUTO

	END
	ELSE BEGIN

		INSERT INTO PRODUTO (DESCRICAO, ID_PRODUTO_TIPO, ID_AUTOR, ID_EDITORA, QUANTIDADE, ATIVO)
		VALUES (UPPER(@I_DESCRICAO), @I_ID_PRODUTO_TIPO, @I_ID_AUTOR, @I_ID_EDITORA, @I_QUANTIDADE, @I_ATIVO)

	END

	SET NOCOUNT OFF;
END
GO
