SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Bruno Oliveira
-- Create date: 25/10/2018
-- Description:	Insere ou altera registros da LOCACAO
-- =============================================
CREATE PROCEDURE dbo.PRC_IU_LOCACAO
	@I_ID_LOCACAO			INT,
	@I_ID_PRODUTO			INT,
	@I_ID_CLIENTE			INT,
	@I_DT_LOCACAO			DATETIME,
	@I_DT_LIMITE_DEVOLUCAO	DATETIME,
	@I_DT_DEVOLUCAO			DATETIME,
	@I_ID_USUARIO			INT
AS
BEGIN
	SET NOCOUNT ON;

    IF EXISTS (SELECT TOP(1) ID_LOCACAO FROM LOCACAO WITH(NOLOCK) WHERE ID_LOCACAO = @I_ID_LOCACAO) BEGIN

		UPDATE LOCACAO
		SET ID_PRODUTO = @I_ID_PRODUTO,
			ID_CLIENTE = @I_ID_CLIENTE,
			DT_LOCACAO = @I_DT_LOCACAO,
			DT_DEVOLUCAO = @I_DT_DEVOLUCAO,
			DT_LIMITE_DEVOLUCAO = @I_DT_LIMITE_DEVOLUCAO,
			ID_USUARIO = @I_ID_USUARIO
		WHERE ID_LOCACAO = @I_ID_LOCACAO;

	END
	ELSE BEGIN

		INSERT INTO LOCACAO (ID_PRODUTO, ID_CLIENTE, DT_LOCACAO, DT_DEVOLUCAO, DT_LIMITE_DEVOLUCAO, ID_USUARIO)
		VALUES (@I_ID_PRODUTO, @I_ID_CLIENTE, @I_DT_LOCACAO, @I_DT_DEVOLUCAO, @I_DT_LIMITE_DEVOLUCAO, @I_ID_USUARIO);

	END

	SET NOCOUNT OFF;
END
GO
